name: Branch Restriction

on:
  push:
    branches-ignore:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sender = process.env.GITHUB_ACTOR;
            const admin = context.repo.owner;
            const creator = (await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.GITHUB_REF.replace('refs/heads/', ''),
              per_page: 1
            })).data[0].author.login;
            if (sender !== admin && sender !== creator) throw new Error('Push denied: only repo admin or branch creator.');
